name: chi
favicon: null
layout_spectrum: 0.535782208899036
typography_spectrum: 0.4008022784255445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7366957147605717
  lightness: 0.7273432132788002
  saturation: 0.9019849037285894
  rhythmicContrast: 0.03836378175765276
purpose: []
